### PR TITLE
Lint 

### PR DESCRIPTION
**Pull request by oliviamiller**
All changes to make the linter pass

### CODE REVIEW

**Comment by mariapatni** [comment]
LGTM!

**Review by mariapatni — APPROVED** [review]
LGTM

**Comment by mariapatni** [comment]
The only thing is on the other PR there were a bunch of printf statements that got removed, are those still deleted?

**Comment by oliviamiller** [comment]
> The only thing is on the other PR there were a bunch of printf statements that got removed from this PR before, are those still deleted?

yep i merged with main!

**Pull request merged**
